conventional-gateway:
    build: ./conventional/request-path/gateway
    container_name: conventional-gateway
    ports:
      - "3201:3201"
    environment:
      PORT: "3201"
      IDENTITY_URL: http://shared-identity:3101/validate-token
      APP_URL: http://conventional-app:3202/execute
    depends_on:
      - shared-identity
      - conventional-app
    restart: unless-stopped

  conventional-app:
    build: ./conventional/request-path/app
    container_name: conventional-app
    expose:
      - "3202"
    environment:
      PORT: "3202"
      DATA_SERVICE_URL: http://conventional-data-service:3203/data-access
      PROVIDER_ADAPTER_URL: http://conventional-provider-adapter:3204/provider-check
    depends_on:
      - conventional-data-service
      - conventional-provider-adapter
    restart: unless-stopped

  conventional-data-service:
    build: ./conventional/request-path/data-service
    container_name: conventional-data-service
    expose:
      - "3203"
    environment:
      PORT: "3203"
    restart: unless-stopped

  conventional-provider-adapter:
    build: ./conventional/request-path/provider-adapter
    container_name: conventional-provider-adapter
    expose:
      - "3204"
    environment:
      PORT: "3204"
    restart: unless-stopped
